import { createStore } from "vuex";

export default createStore({
  state: {
    itemList: [
      {
        id: 1,
        brand: "Apple",
        model: "Apple iPhone 12",
        year: 2020,
        screenSize: 6.1,
        country: "Китай",
        memoryStorage: 128,
        screenUpdateFrequency: 60,
        nfc: false,
        esim: true,
        qiCharge: true,
        price: 81990,
        img: "iphone12.svg",
      },
      {
        id: 2,
        brand: "Xiaomi",
        model: "Xiaomi Mi 11 Lite",
        year: 2021,
        screenSize: 6.55,
        country: "Китай",
        memoryStorage: 128,
        screenUpdateFrequency: 90,
        nfc: true,
        esim: true,
        qiCharge: false,
        price: 27490,
        img: "xiaomi11.svg",
      },
      {
        id: 3,
        brand: "Samsung",
        model: "Samsung Galaxy A72",
        year: 2021,
        screenSize: 6.7,
        country: "Вьетнам",
        memoryStorage: 128,
        screenUpdateFrequency: 90,
        nfc: true,
        esim: false,
        qiCharge: true,
        price: 32890,
        img: "samsunga72.svg",
      },
      {
        id: 4,
        brand: "Apple",
        model: "Apple iPhone Xr",
        year: 2018,
        screenSize: 6.4,
        country: "Китай",
        memoryStorage: 64,
        screenUpdateFrequency: 60,
        nfc: true,
        esim: true,
        qiCharge: true,
        price: 22890,
        img: "iphonexr.svg",
      },
      {
        id: 5,
        brand: "Samsung",
        model: "Samsung Galaxy S21",
        year: 2021,
        screenSize: 6.7,
        country: "Вьетнам",
        memoryStorage: 128,
        screenUpdateFrequency: 90,
        nfc: true,
        esim: false,
        qiCharge: true,
        price: 32890,
        img: "samsunggalaxys21.svg",
      },
      {
        id: 6,
        brand: "Realme",
        model: "Realme 8 Pro",
        year: 2021,
        screenSize: 6.3,
        country: "Китай",
        memoryStorage: 128,
        screenUpdateFrequency: 90,
        nfc: true,
        esim: false,
        qiCharge: true,
        price: 12890,
        img: "realme8pro.svg",
      },
      {
        id: 7,
        brand: "Iphone",
        model: "Iphone X",
        year: 2017,
        screenSize: 6.3,
        country: "Китай",
        memoryStorage: 32,
        screenUpdateFrequency: 60,
        nfc: true,
        esim: false,
        qiCharge: true,
        price: 15890,
        img: "iphonex.png",
      },
    ],
  },
  getters: {},
  mutations: {},
  actions: {},
  modules: {},
});
